ci: fix deploy job status and tf lock in fail-fast

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -57,6 +57,7 @@ jobs:
     strategy:
       matrix:
         env: ${{ fromJson(needs.filter-envs.outputs.envs) }}
+    continue-on-error: true
     runs-on: ubuntu-latest
     name: 'CI/CD: ${{ matrix.env }}'
     permissions:
@@ -72,6 +73,7 @@ jobs:
     steps:
       - run: echo "Deploying against ${{ matrix.env }} environment"
       - uses: actions/checkout@v4
+        id: checkout
         with:
           ref: ${{ github.head_ref || github.ref_name }}
 
@@ -83,9 +85,11 @@ jobs:
           private_key: ${{ secrets.NOTIFYCAL_CICD_APP_SECRET }}
 
       - name: Hack for github internal repo access :(
+        id: gh_internal_repo_access
         run: git config --global url."https://foo:${{ steps.gh-app-auth.outputs.token }}@github.com".insteadOf ssh://git@github.com
 
       - name: Configure AWS Credentials
+        id: config_aws_credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-region: ${{ env.AWS_REGION }}
@@ -112,6 +116,7 @@ jobs:
           TG_VERSION: ${{ steps.get_tf_tg_version.outputs.terragrunt_version }}
 
       - name: Install OpenTofu and Terragrunt
+        id: tf_tg_install
         # Only if there is no cache
         if: steps.tbinaries-cache.outputs.cache-hit != 'true'
         run: |
@@ -136,6 +141,7 @@ jobs:
           TG_VERSION: ${{ steps.get_tf_tg_version.outputs.terragrunt_version }}
 
       - name: Install service-discovery tool
+        id: service_discovery_install_tool
         run: |
           pushd service-registration > /dev/null
           cp service-discovery.py /usr/local/bin/service-discovery
@@ -144,6 +150,7 @@ jobs:
           service-discovery -h
 
       - name: Terragrunt init
+        id: tg_init
         run: |
           cd envs/${{ matrix.env }}
           terragrunt run-all init
@@ -153,6 +160,7 @@ jobs:
           TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
 
       - name: Terragrunt plan
+        id: tg_plan
         run: |
           cd envs/${{ matrix.env }}
           terragrunt run-all plan
@@ -161,6 +169,7 @@ jobs:
           TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
 
       - name: Terragrunt apply
+        id: tg_apply
         run: |
           cd envs/${{ matrix.env }}
           terragrunt run-all apply
@@ -170,3 +179,41 @@ jobs:
           TERRAGRUNT_NON_INTERACTIVE: "true"
           GH_TOKEN: ${{ steps.gh-app-auth.outputs.token }}
           TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+      
+      - name: Write job status to file
+        if: always()
+        id: write_job_status
+        run: |
+          if [[ ${{ contains(steps.*.outcome, 'failure') }} == "true" ]]; then
+            echo "failure" > status.txt
+          else
+            echo "success" > status.txt
+          fi
+      
+      - name: Upload status artifact
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: result-${{ matrix.env }}
+          path: status.txt
+
+  postflight:
+    runs-on: ubuntu-latest
+    needs: deploy
+    if: always()
+    steps:
+      - name: Download job status artifact
+        uses: actions/download-artifact@v4
+        with:
+          pattern: result-*
+          path: results
+      - run: ls -la results 
+      - name: Set workflow outcome
+        run: |
+          if grep -xq 'failure' results/*/status.txt; then
+            echo "At least one job failed. Failing workflow"
+            exit 1
+          else
+            echo "All jobs passed"
+          fi
+          
